# Generated by Django 5.2.3 on 2025-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
