# Generated by Django 5.2.3 on 2025-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_cancellation_fee_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
