# Generated by Django 5.2.3 on 2025-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_proposed_date_reservation_proposed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
